package adproc;

import java.awt.Color;
import java.math.BigDecimal;

/**
 *the main window display
 * @author UP822718, UP918156, UP879389, UP821837
 */
public class mainWindow extends javax.swing.JDialog {
    int lastBox;
    /**
     * Creates new form mainWindow
     */
    int grade = 1;
    OrderingBackEnd boxOrder =null;
    
    /**
    *constructor to make a box
     * @param parent  parent window frame
     * @param modal   the window mode 
    */
    public mainWindow(java.awt.Frame parent, boolean modal)
    {
        
        super(parent, modal);
        initComponents();
        boxOrder = new OrderingBackEnd();
        boxUpdater();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        checkConres = new javax.swing.JCheckBox();
        checkBottom = new javax.swing.JCheckBox();
        checkSeltop = new javax.swing.JCheckBox();
        Colour = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        lblPrices = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JLabel();
        spinQuantity = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spinColour = new javax.swing.JSpinner();
        txtWidth = new javax.swing.JTextField();
        txtLength = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInvoice = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Make A box"));

        jLabel2.setText("Width (M)");

        jLabel3.setText("Height (M)");

        jLabel1.setText("Length (M)");

        checkConres.setText("Reinforced Corners");
        checkConres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updataBox(evt);
            }
        });

        checkBottom.setText("Reinforced Bottom");
        checkBottom.setToolTipText("");
        checkBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updataBox(evt);
            }
        });

        checkSeltop.setText("Sealable Top");
        checkSeltop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updataBox(evt);
            }
        });

        Colour.setText("Colour");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add Box");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        lblPrices.setText("jLabel4");

        txtTotalPrice.setText("Total Price");

        spinQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 900, 1));
        spinQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updataBox2(evt);
            }
        });

        jLabel6.setText("Quantity");
        jLabel6.setToolTipText("");

        jLabel7.setText("Grade");

        spinColour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 2, 1));
        spinColour.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinColourStateChanged(evt);
            }
        });

        txtWidth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtWidth.setText("0.1");
        txtWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWidthActionPerformed(evt);
            }
        });
        txtWidth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUpdate(evt);
            }
        });

        txtLength.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLength.setText("0.1");
        txtLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWidthActionPerformed(evt);
            }
        });
        txtLength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUpdate(evt);
            }
        });

        txtHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHeight.setText("0.1");
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWidthActionPerformed(evt);
            }
        });
        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUpdate(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmdUpdae(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Order"));

        txtInvoice.setEditable(false);
        txtInvoice.setColumns(20);
        txtInvoice.setRows(5);
        txtInvoice.setEnabled(false);
        jScrollPane1.setViewportView(txtInvoice);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Delete Box");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalPrice)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkSeltop)
                            .addComponent(lblPrices)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(spinQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtWidth, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                                    .addComponent(txtHeight))
                                                .addGap(24, 24, 24))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(checkConres)
                                .addGap(18, 18, 18)
                                .addComponent(checkBottom))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Colour)
                        .addGap(4, 4, 4)
                        .addComponent(spinColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(13, 13, 13)
                        .addComponent(BtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spinQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkConres)
                            .addComponent(checkBottom))
                        .addGap(4, 4, 4)
                        .addComponent(checkSeltop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Colour)
                            .addComponent(spinColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblPrices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(BtnAdd))
                        .addGap(4, 4, 4)
                        .addComponent(txtTotalPrice))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName("height");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Make a Box");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    *update form ActionEvent  in check boxes 
    * @param evt  event from update
    */
    private void updataBox(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updataBox
        boxUpdater();
    }//GEN-LAST:event_updataBox
    /**
    *update form ChangeEvent  in  spinQuantity
     * @param evt  event from update
    */
    private void updataBox2(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_updataBox2
        boxUpdater();
    }//GEN-LAST:event_updataBox2
                     
    /**
    *allows the user to add to order form button press
    * @param evt  event from update
    */
    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
       Box box  =boxUpdater() ;
       if (box != null)
       {
        boxOrder.SetBox(box);
        BigDecimal value = new BigDecimal(boxOrder.GetPrices());
        value = value.setScale(2, BigDecimal.ROUND_HALF_UP);
        txtTotalPrice.setText("Total price £"+ value);
        txtInvoice.setText(boxOrder.GetShowoffs());
        lastBox= boxOrder.GetBoxNum();
       }
        
               
    }//GEN-LAST:event_BtnAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jComboBox1.setSelectedIndex(0);
       spinQuantity.setValue(1);
       spinColour.setValue(0);
       txtWidth.setText("0.1");
       txtHeight.setText("0.1");
       txtLength.setText("0.1");
       checkBottom.setSelected(false);
       checkConres.setSelected(false);
       checkSeltop.setSelected(false);
       boxUpdater();
         
    }//GEN-LAST:event_jButton1ActionPerformed
                      
    /**
    *update form ActionEvent  in  Text box (only after hiting enter)
    * @param evt  event from update
    */
    private void txtWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWidthActionPerformed
        boxUpdater();
    }//GEN-LAST:event_txtWidthActionPerformed
                      
    /**
    *update form ActionEvent  in  Text box
    * @param evt  event from update
    */
    private void txtUpdate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdate
boxUpdater();
    }//GEN-LAST:event_txtUpdate
                      
    /**
    *update form ItemEvent  in  Combobox
    * @param evt  event from update
    */
    private void cmdUpdae(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmdUpdae
                                            
       //System.out.println("not top one");
        switch(jComboBox1.getSelectedItem().toString())
        {
            case "Grade 1":
                grade = 1 ;
                break;
            case "Grade 2":
                grade = 2 ;
                break;
            case "Grade 3":
                grade = 3 ;
                break;
            case "Grade 4":
                grade = 4 ;
                break;
            case "Grade 5":
                grade = 5 ;
                break;
        }
           boxUpdater();
    }//GEN-LAST:event_cmdUpdae

    private void spinColourStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinColourStateChanged
                            
        boxUpdater();
    }//GEN-LAST:event_spinColourStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(boxOrder.GetBoxNum()!= 0)
        {
            
            boxOrder.RemoveBox(lastBox - 1);
            lastBox = lastBox - 1;
            txtInvoice.setText(boxOrder.GetShowoffs());
            BigDecimal value = new BigDecimal(boxOrder.GetPrices());
            value = value.setScale(2, BigDecimal.ROUND_HALF_UP);
            txtTotalPrice.setText("Total price £"+ value);
        }
        else{lblPrices.setText("Order is Empty, No boxes to delete!");}
    }//GEN-LAST:event_jButton2ActionPerformed
                  
                      
    /**
    *validate user input after it has bean inputed and update the gui
     * @return a valid box
    */
    private Box boxUpdater()
    {
        int Quantity =  (Integer) spinQuantity.getValue();
        double length;
        double height;
        double width;
        try 
        {
            length = Double.parseDouble(txtLength.getText());
            height = Double.parseDouble(txtHeight.getText());
            width = Double.parseDouble(txtWidth.getText());
        }
        catch (Exception e)
        {
                lblPrices.setForeground(Color.red);
                lblPrices.setText("Invalid Box Input!, Please input numbers for length, height & width");
                return null;
                
        }
        if (length <= 0 ||height <= 0 || width <= 0 || Quantity <= 0) {
                lblPrices.setForeground(Color.red);
                lblPrices.setText("Invalid Box Input!, please input non-zero or postive values");
                return null;
            
        }
        
        if (length >= 900 ||height >= 900 || width >= 900) {
                lblPrices.setForeground(Color.red);
                lblPrices.setText("Invalid Box Input!, Maximum value reached, please try a smaller value");
                return null;
            
        }
        boolean Bottom = checkBottom.isSelected();
        boolean Conres = checkConres.isSelected();
        boolean seltop = checkSeltop.isSelected();
        int NumerOfColur = (Integer) spinColour.getValue();
        Box box = boxOrder.MakeBox(NumerOfColur, Bottom, Conres, seltop, grade, length, height, width,Quantity);
            try
            {
                lblPrices.setForeground(Color.black);
                BigDecimal value = new BigDecimal(box.price());
                value = value.setScale(2, BigDecimal.ROUND_HALF_UP);
                lblPrices.setText("This box costs £"+value);
            }
            catch (Exception e)
            {
                lblPrices.setForeground(Color.red);
                lblPrices.setText("Sorry, we can't make this box, please try changing the box's values");
            }
        return box;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JLabel Colour;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBottom;
    private javax.swing.JCheckBox checkConres;
    private javax.swing.JCheckBox checkSeltop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrices;
    private javax.swing.JSpinner spinColour;
    private javax.swing.JSpinner spinQuantity;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextArea txtInvoice;
    private javax.swing.JTextField txtLength;
    private javax.swing.JLabel txtTotalPrice;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables
}